version: '3'
services:

  redis:
    image: 'redis'
    volumes:
      - redis_data:/data

  telbot:
#    image: sepehr79m/telbot
    build: .
    environment:
      SPRING_REDIS_HOST: redis

volumes:
  redis_data:
    external: false
